### ISSUE TITLE
Master commit (fe73ebd) linking fails.

### ISSUE THREAD

**Issue by DrJohnDale** [GooFit/Minuit2#3]
Hi,

While trying to build today I found that the latest commit fails to link with visual studio where as 2 commits  (968ec5b) does link.

The linker is looking for lib minuit2Common.lib which does not exist.

Regards,

John

**Comment by henryiii** [comment]
@DrJohnDale I merged the new stand-alone build system back into ROOT master, and have not been keeping this library up. You can now directly add subdirectory or build from `root/math/minuit2` without building or touching the rest of ROOT. Since I don't want to clone all of ROOT for GooFit, I'd like to replace the current repository with a new export of the one in ROOT. So please check after the next commit and see if the problem persists! (1-3 days hopefully)

**Comment by henryiii** [comment]
I have updated this repository with the 6.14.0 tag as well as the latest changes in upstream ROOT. Please retry and see if the problem persists, in which case, I can develop a patch for upstream ROOT. Thanks!

**Comment by DrJohnDale** [comment]
Hi, The head builds and runs now. Thanks for the support.
